{"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [DELETE] \"/v1/likes/delete\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"exception_object_id":32840,"id":0,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'"},{"exception_object_id":32840,"id":1,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"},{"exception_object_id":32840,"id":2,"trace":"railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'"},{"exception_object_id":32840,"id":3,"trace":"railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'"},{"exception_object_id":32840,"id":4,"trace":"activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'"},{"exception_object_id":32840,"id":5,"trace":"activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'"},{"exception_object_id":32840,"id":6,"trace":"activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'"},{"exception_object_id":32840,"id":7,"trace":"railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'"},{"exception_object_id":32840,"id":8,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"},{"exception_object_id":32840,"id":9,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'"},{"exception_object_id":32840,"id":10,"trace":"rack (2.2.3) lib/rack/runtime.rb:22:in `call'"},{"exception_object_id":32840,"id":11,"trace":"activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"},{"exception_object_id":32840,"id":12,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"exception_object_id":32840,"id":13,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'"},{"exception_object_id":32840,"id":14,"trace":"rack (2.2.3) lib/rack/sendfile.rb:110:in `call'"},{"exception_object_id":32840,"id":15,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'"},{"exception_object_id":32840,"id":16,"trace":"rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'"},{"exception_object_id":32840,"id":17,"trace":"railties (6.0.3.2) lib/rails/engine.rb:527:in `call'"},{"exception_object_id":32840,"id":18,"trace":"puma (4.3.5) lib/puma/configuration.rb:228:in `call'"},{"exception_object_id":32840,"id":19,"trace":"puma (4.3.5) lib/puma/server.rb:713:in `handle_request'"},{"exception_object_id":32840,"id":20,"trace":"puma (4.3.5) lib/puma/server.rb:472:in `process_client'"},{"exception_object_id":32840,"id":21,"trace":"puma (4.3.5) lib/puma/server.rb:328:in `block in run'"},{"exception_object_id":32840,"id":22,"trace":"puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'"}],"Full Trace":[{"exception_object_id":32840,"id":0,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'"},{"exception_object_id":32840,"id":1,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"},{"exception_object_id":32840,"id":2,"trace":"railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'"},{"exception_object_id":32840,"id":3,"trace":"railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'"},{"exception_object_id":32840,"id":4,"trace":"activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'"},{"exception_object_id":32840,"id":5,"trace":"activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'"},{"exception_object_id":32840,"id":6,"trace":"activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'"},{"exception_object_id":32840,"id":7,"trace":"railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'"},{"exception_object_id":32840,"id":8,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"},{"exception_object_id":32840,"id":9,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'"},{"exception_object_id":32840,"id":10,"trace":"rack (2.2.3) lib/rack/runtime.rb:22:in `call'"},{"exception_object_id":32840,"id":11,"trace":"activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"},{"exception_object_id":32840,"id":12,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"exception_object_id":32840,"id":13,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'"},{"exception_object_id":32840,"id":14,"trace":"rack (2.2.3) lib/rack/sendfile.rb:110:in `call'"},{"exception_object_id":32840,"id":15,"trace":"actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'"},{"exception_object_id":32840,"id":16,"trace":"rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'"},{"exception_object_id":32840,"id":17,"trace":"railties (6.0.3.2) lib/rails/engine.rb:527:in `call'"},{"exception_object_id":32840,"id":18,"trace":"puma (4.3.5) lib/puma/configuration.rb:228:in `call'"},{"exception_object_id":32840,"id":19,"trace":"puma (4.3.5) lib/puma/server.rb:713:in `handle_request'"},{"exception_object_id":32840,"id":20,"trace":"puma (4.3.5) lib/puma/server.rb:472:in `process_client'"},{"exception_object_id":32840,"id":21,"trace":"puma (4.3.5) lib/puma/server.rb:328:in `block in run'"},{"exception_object_id":32840,"id":22,"trace":"puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'"}]}}